name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://eddiewelker.com/rss.xml"
          max_post_count: 5
          template: "* [$title]($url)$newline"
          tag_post_pre_newline: true
          disable_html_encoding: true
