name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://eddiewelker.com/rss.xml"
          max_post_count: 5
          # The empty line below the title forces a true Markdown line break
          template: |
            * [$title]($url)

          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
